#App specific makefile for UWRT Mars Rover 2017
BASE_PATH = ../..

#filename of outputed .elf and .bin files
PROJECT = pwmic_test

#the folder the current app is in
APP_FOLDER = pwmic_test

include $(BASE_PATH)/makefile
