#App specific makefile for UWRT Mars Rover 2017
BASE_PATH = ..

#filename of outputed .elf and .bin files
PROJECT = can_driver

#the folder the current app is in
APP_FOLDER = canlib

include $(BASE_PATH)/makefile
