#App specific makefile for UWRT Mars Rover 2017
BASE_PATH = ..

#filename of outputed .elf and .bin files
PROJECT = blinky_out

#the folder the current app is in
APP_FOLDER = blinky

include $(BASE_PATH)/makefile