#App specific makefile for UWRT Mars Rover 2017
BASE_PATH = ../..

#filename of outputed .elf and .bin files
PROJECT = safety_a

#the folder the current app is in
APP_FOLDER = safety_a

include $(BASE_PATH)/makefile
