#App specific makefile for UWRT Mars Rover 2017
BASE_PATH = ../..

#filename of outputed .elf and .bin files
PROJECT = sci_mdl

#the folder the current app is in
APP_FOLDER = science_module

include $(BASE_PATH)/makefile
