#App specific makefile for UWRT Mars Rover 2017
BASE_PATH = ../..

#filename of outputed .elf and .bin files
PROJECT = arm_control

#the folder the current app is in
APP_FOLDER = arm_control

include $(BASE_PATH)/makefile
