#App specific makefile for UWRT Mars Rover 2017
BASE_PATH = ..

#filename of outputed .elf and .bin files
PROJECT = pwm_driver

#the folder the current app is in
APP_FOLDER = pwmlib

include $(BASE_PATH)/makefile
