#App specific makefile for UWRT Mars Rover 2017
BASE_PATH = ../..

#filename of outputed .elf and .bin files
PROJECT = i2c_test

#the folder the current app is in
APP_FOLDER = i2c_test

include $(BASE_PATH)/makefile
